### ISSUE TITLE
can't find point_cloud.py, commit 048c59bea4b94

### ISSUE THREAD

**Issue by triffid** [kaosat-dev/Doboz-web#2]
triffid@aachenar ~/Doboz/source $ python run.py 
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    from Core.print_server.print_server import *
  File "/home/triffid/Doboz/source/Core/print_server/print_server.py", line 14, in <module>
    from point_cloud import PointCloudBuilder,PointCloud,Point
ImportError: No module named point_cloud
triffid@aachenar ~/Doboz/source [1] $ find | grep -i point
./Core/Tools/point_cloud_builder.py
./Core/Tools/point_cloud2.py

**Comment by kaosat-dev** [comment]
Thanks for that triffid, seems the project was not cleaned correctly last time i pushed to github: should be fixed now
