### ISSUE TITLE
more can't find module errors, commit b87af8864a2

### ISSUE THREAD

**Issue by triffid** [kaosat-dev/Doboz-web#3]
triffid@aachenar ~/Projects/Doboz/source $ python run.py 
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    from Core.hardwareNodes.reprap.reprap_node import ReprapNode
  File "/home/triffid/Projects/Doboz/source/Core/hardwareNodes/reprap/reprap_node.py", line 11, in <module>
    from Core.connectors.event_sys import *
ImportError: No module named event_sys
triffid@aachenar ~/Projects/Doboz/source [1] $ find | grep event
./Core/Tools/event_sys.py
./Core/Tools/event_sys.pyc

I don't understand python enough to debug these myself unfortunately.. one day I'll learn my python, this is not it

**Comment by kaosat-dev** [comment]
Wow thanks a lot for the help Triffid! i actually thing i know where this is coming from , gotta investigate , it should be fixed in the latest version now !
